import { defineStore } from 'pinia';
import { ref } from 'vue';
import type { Task } from './types';

export const useTaskStore = defineStore('task', () => {
	const tasks = ref<Task[]>([
		{
			id: 'c1-1',
			title: '1. Design onboarding flow',
			description: 'Create wireframes for the onboarding screens',
			priority: 'high',
			status: 'todo',
			createdAt: '2026-04-01T09:00:00Z',
			assigneesId: ['user-1'],
			dueDate: null,
		},
		{
			id: 'c1-2',
			title: '2. Write API documentation',
			description: 'Document all REST endpoints with examples',
			priority: 'medium',
			status: 'todo',
			createdAt: '2026-04-01T10:00:00Z',
			assigneesId: ['user-2'],
			dueDate: null,
		},
		{
			id: 'c1-3',
			title: '3. Refactor auth module',
			description: 'Split auth logic into composables',
			priority: 'medium',
			status: 'todo',
			createdAt: '2026-04-01T11:00:00Z',
			assigneesId: [],
			dueDate: null,
		},
		{
			id: 'c1-4',
			title: '4. Create landing page',
			description: null,
			priority: 'low',
			status: 'todo',
			createdAt: '2026-04-01T12:00:00Z',
			assigneesId: ['user-3'],
			dueDate: null,
		},
		{
			id: 'c1-5',
			title: '5. Set up analytics',
			description: 'Integrate product analytics SDK',
			priority: 'low',
			status: 'todo',
			createdAt: '2026-04-01T13:00:00Z',
			assigneesId: ['user-1'],
			dueDate: null,
		},
		{
			id: 'c1-6',
			title: '6. Add dark mode toggle',
			description: 'Persist preference in localStorage',
			priority: null,
			status: 'todo',
			createdAt: '2026-04-01T14:00:00Z',
			assigneesId: [],
			dueDate: null,
		},
		{
			id: 'c1-7',
			title: '7. Optimize image loading',
			description: 'Add lazy loading and responsive srcset',
			priority: 'medium',
			status: 'todo',
			createdAt: '2026-04-01T15:00:00Z',
			assigneesId: ['user-2'],
			dueDate: null,
		},
		{
			id: 'c2-1',
			title: '1. Build user profile page',
			description: 'Layout with avatar, bio and stats',
			priority: 'high',
			status: 'inProgress',
			createdAt: '2026-04-02T09:00:00Z',
			assigneesId: ['user-1'],
			dueDate: null,
		},
		{
			id: 'c2-2',
			title: '2. Integrate payment gateway',
			description: 'Stripe checkout for pro plan',
			priority: 'high',
			status: 'inProgress',
			createdAt: '2026-04-02T10:00:00Z',
			assigneesId: ['user-2', 'user-3'],
			dueDate: null,
		},
		{
			id: 'c2-3',
			title: '3. Add search functionality',
			description: 'Client-side fuzzy search over tasks',
			priority: 'medium',
			status: 'inProgress',
			createdAt: '2026-04-02T11:00:00Z',
			assigneesId: ['user-1'],
			dueDate: null,
		},
		{
			id: 'c2-4',
			title: '4. Create notification system',
			description: null,
			priority: 'medium',
			status: 'inProgress',
			createdAt: '2026-04-02T12:00:00Z',
			assigneesId: [],
			dueDate: null,
		},
		{
			id: 'c2-5',
			title: '5. Implement file upload',
			description: 'Drag and drop attachments to tasks',
			priority: 'low',
			status: 'inProgress',
			createdAt: '2026-04-02T13:00:00Z',
			assigneesId: ['user-3'],
			dueDate: null,
		},
		{
			id: 'c2-6',
			title: '6. Add multi-language support',
			description: 'i18n setup with EN and UK locales',
			priority: null,
			status: 'inProgress',
			createdAt: '2026-04-02T14:00:00Z',
			assigneesId: ['user-2'],
			dueDate: null,
		},
		{
			id: 'c2-7',
			title: '7. Improve form validation',
			description: 'Unified error display across inputs',
			priority: 'low',
			status: 'inProgress',
			createdAt: '2026-04-02T15:00:00Z',
			assigneesId: [],
			dueDate: null,
		},
		{
			id: 'c3-1',
			title: '1. Setup project structure',
			description: 'Feature-Sliced Design layers',
			priority: 'high',
			status: 'done',
			createdAt: '2026-03-25T09:00:00Z',
			assigneesId: ['user-1'],
			dueDate: null,
		},
		{
			id: 'c3-2',
			title: '2. Configure Biome',
			description: 'Formatter and linter rules',
			priority: 'medium',
			status: 'done',
			createdAt: '2026-03-25T10:00:00Z',
			assigneesId: ['user-2'],
			dueDate: null,
		},
		{
			id: 'c3-3',
			title: '3. Install dependencies',
			description: null,
			priority: 'low',
			status: 'done',
			createdAt: '2026-03-25T11:00:00Z',
			assigneesId: [],
			dueDate: null,
		},
		{
			id: 'c3-4',
			title: '4. Create initial README',
			description: 'Getting started section',
			priority: 'low',
			status: 'done',
			createdAt: '2026-03-25T12:00:00Z',
			assigneesId: ['user-3'],
			dueDate: null,
		},
		{
			id: 'c3-5',
			title: '5. Set up Git repository',
			description: 'Push to GitHub, add branch protection',
			priority: null,
			status: 'done',
			createdAt: '2026-03-25T13:00:00Z',
			assigneesId: ['user-1'],
			dueDate: null,
		},
		{
			id: 'c3-6',
			title: '6. Configure Vite build',
			description: 'Path aliases and env handling',
			priority: 'medium',
			status: 'done',
			createdAt: '2026-03-25T14:00:00Z',
			assigneesId: ['user-2'],
			dueDate: null,
		},
		{
			id: 'c3-7',
			title: '7. Add basic routing',
			description: 'Main and Board pages wired up',
			priority: 'medium',
			status: 'done',
			createdAt: '2026-03-25T15:00:00Z',
			assigneesId: ['user-3'],
			dueDate: null,
		},
	]);

	const getTaskById = (id: string): Task | null => {
		return tasks.value.find((task) => task.id === id) ?? null;
	};

	const getTasksByIds = (ids: string[] | undefined): Task[] => {
		if (!ids) return [];

		return ids
			.map((id: string) => tasks.value.find((task: Task) => task.id === id))
			.filter((mappedItem: Task | undefined) => mappedItem !== undefined);
	};

	return { getTasksByIds, getTaskById };
});
